### ISSUE TITLE
Eror 

### ISSUE THREAD

**Issue by Ardilll195** [shareithub/grass-bot#1]
Pas jalanin python run_proxy.txt muncul ini 
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/nodepay/run_proxy.py", line 10, in <module>
    from curl_cffi import requests
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/curl_cffi/__init__.py", line 19, in <module>
    from .__version__ import __curl_version__, __description__, __title__, __version__  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/curl_cffi/__version__.py", line 3, in <module>
    from .curl import Curl
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/curl_cffi/curl.py", line 9, in <module>
    from ._wrapper import ffi, lib
ImportError: dlopen failed: library "libcurl-impersonate-chrome.so.4" not found: needed by /data/data/com.termux/files/usr/lib/python3.12/site-packages/curl_cffi/_wrapper.abi3.so in namespace (default)
![Screenshot_2024-12-13-07-33-25-361_com termux](https://github.com/user-attachments/assets/4b978331-d74a-4465-a74b-8abce1f3d7e3)

**Comment by rahmap** [comment]
lol you noob
